# Permalinks
permalink:           pretty

# Setup
title:               bootMode
tagline:             rm -rf
url:                 bootmo.de
paginate:            10
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Victor Niu
  url:               victorniu.com
  email:             bniu2@illinois.edu

# Custom vars
version:             0.2.1
github:
  repo:              https://github.com/developermode/bootmode

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
